2024-06-03 22:50:12 [INFO][io.lettuce.core.protocol.CommandHandler][log][217]-> null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2024-06-03 22:50:12 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was /127.0.0.1:6379
2024-06-03 22:50:14 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:50:18 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:50:20 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:50:25 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:50:27 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:50:32 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:50:34 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:50:39 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:50:41 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:50:45 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:50:47 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:50:56 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:50:58 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:51:14 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:51:16 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:51:46 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:51:48 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:52:18 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:52:20 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:52:50 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:52:52 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:53:23 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:53:25 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:53:55 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:53:57 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:54:27 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:54:29 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:54:59 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:55:01 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:55:31 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:55:33 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:56:03 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:56:05 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:56:35 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:56:37 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:57:07 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:57:09 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:57:39 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:57:41 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:58:11 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:58:13 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:58:44 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:58:46 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:59:16 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:59:18 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 22:59:48 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 22:59:50 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:00:20 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:00:22 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:00:52 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:00:54 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:01:24 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:01:26 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:01:56 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:01:58 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:02:28 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:02:30 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:03:00 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:03:02 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:03:32 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:03:34 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:04:05 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:04:07 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:04:37 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:04:39 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:05:09 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:05:11 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:05:41 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:05:43 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:06:13 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:06:15 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:06:45 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:06:47 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:07:17 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:07:19 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:07:49 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:07:51 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:08:21 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:08:23 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:08:53 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:08:55 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:09:26 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:09:28 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:09:58 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:10:00 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:10:30 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:10:32 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:11:02 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:11:04 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:11:34 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:11:36 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:12:06 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:12:08 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:12:38 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:12:40 [WARN][io.lettuce.core.protocol.ConnectionWatchdog][log][151]-> Cannot reconnect to [127.0.0.1:6379]: Connection refused: no further information: /127.0.0.1:6379
2024-06-03 23:13:10 [INFO][io.lettuce.core.protocol.ConnectionWatchdog][log][171]-> Reconnecting, last destination was 127.0.0.1:6379
2024-06-03 23:13:10 [INFO][io.lettuce.core.protocol.ReconnectionHandler][lambda$null$3][174]-> Reconnected to 127.0.0.1:6379
